[project]
name = "tutorial_se"
version = "1.0.0"
description = "My first Python package"
requires-python = ">=3.8"
authors = [
    {name = "Vytautas Jancauskas", email = "vytautas.jancauskas@dlr.de"}
]
dependencies = [
    "numpy",
    "pandas",
   ]